// <auto-generated />
using System;
using BoozeClues.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BoozeClues.Migrations
{
    [DbContext(typeof(BoozeCluesDbContext))]
    [Migration("20240619202524_addedimagecreate")]
    partial class addedimagecreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BoozeClues.Models.CocktailRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GlassTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GlassTypeId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("CocktailRecipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A refreshing tequila-based cocktail with lime juice and Cointreau.",
                            GlassTypeId = 1,
                            Image = "https://recipes.net/wp-content/uploads/2023/05/classic-margarita-recipe_780ef5cf753cf58502c26278fa094aa1.jpeg",
                            Instructions = "Shake all ingredients with ice, then strain into a chilled glass.",
                            Name = "Margarita",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "A classic cocktail made with bourbon, simple syrup, and bitters.",
                            GlassTypeId = 3,
                            Image = "https://www.liquor.com/thmb/IgE3k1GbbNMWVCpmFI3-kKSx3eM=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/bourbon-old-fashioned-4000x4000-primary-ig-f0ce04bec6754db187ab1e8a16fd45c3.jpg",
                            Instructions = "Stir ingredients with ice, then strain into a glass over ice.",
                            Name = "Old Fashioned",
                            UserProfileId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "A stylish cocktail featuring vodka, triple sec, lime juice, and cranberry juice.",
                            GlassTypeId = 2,
                            Image = "https://toriavey.com/images/2011/03/The-Kosher-Cosmo-1.jpeg",
                            Instructions = "Shake all ingredients with ice, then strain into a chilled glass.",
                            Name = "Cosmopolitan",
                            UserProfileId = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "A minty and refreshing cocktail made with rum, lime juice, and soda water.",
                            GlassTypeId = 1,
                            Image = "https://mixthatdrink.com/wp-content/uploads/2009/03/mojito-750x1126.jpg",
                            Instructions = "Muddle mint leaves with lime juice and sugar, then add rum and top up with soda water.",
                            Name = "Mojito",
                            UserProfileId = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "A tropical cocktail made with rum, coconut cream, and pineapple juice.",
                            GlassTypeId = 1,
                            Image = "https://cookingwithcurls.com/wp-content/uploads/2015/04/Classic-Pi%C3%B1a-Colada-A-sweet-tropical-cocktail-made-with-rum-pineapple-juice-and-coconut-cream-cookingwithcurls.com_.jpg",
                            Instructions = "Blend all ingredients with ice until smooth, then serve in a chilled glass.",
                            Name = "Pina Colada",
                            UserProfileId = 5
                        },
                        new
                        {
                            Id = 6,
                            Description = "A classic cocktail made with gin and a touch of blue curacao.",
                            GlassTypeId = 2,
                            Image = "https://www.liquor.com/thmb/uiVEGvb2jIR-Y_IyKZCIPrxrt-U=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/vodka-martini-1500x1500-hero-080af5bb8ff04851a9c0ecf77a88a818.jpg",
                            Instructions = "Stir ingredients with ice, then strain into a chilled glass.",
                            Name = "Martini",
                            UserProfileId = 6
                        },
                        new
                        {
                            Id = 7,
                            Description = "A fruity cocktail made with rum, maraschino liqueur, peach schnapps, and lemon juice.",
                            GlassTypeId = 4,
                            Image = "https://www.aberdeenskitchen.com/wp-content/uploads/2016/06/Tropical-Mai-Tai-Cocktail-4-680x1024.jpg",
                            Instructions = "Shake all ingredients with ice, then strain into a glass over ice.",
                            Name = "Mai Tai",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "A spicy and refreshing cocktail made with vodka, lime juice, and ginger beer.",
                            GlassTypeId = 1,
                            Image = "https://www.thewinecellargroup.com/wp-content/uploads/2019/09/mule.jpg",
                            Instructions = "Combine ingredients in a glass with ice, then stir gently.",
                            Name = "Moscow Mule",
                            UserProfileId = 2
                        },
                        new
                        {
                            Id = 9,
                            Description = "A tangy cocktail made with bourbon, simple syrup, and lemon juice.",
                            GlassTypeId = 3,
                            Image = "https://www.whisky-sour.com/images/16x9/whiskey-sour-16x9.jpg",
                            Instructions = "Shake all ingredients with ice, then strain into a glass over ice.",
                            Name = "Whiskey Sour",
                            UserProfileId = 3
                        },
                        new
                        {
                            Id = 10,
                            Description = "A sweet and sour cocktail made with rum, simple syrup, and lime juice.",
                            GlassTypeId = 5,
                            Image = "https://d194ip2226q57d.cloudfront.net/images/daiquiri.original.png",
                            Instructions = "Shake all ingredients with ice, then strain into a chilled glass.",
                            Name = "Daiquiri",
                            UserProfileId = 4
                        },
                        new
                        {
                            Id = 11,
                            Description = "A colorful cocktail made with tequila, orange juice, and grenadine.",
                            GlassTypeId = 1,
                            Image = "https://www.liquor.com/thmb/jjV_5roCvfnVgzYU89UROFguRpM=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/tequila-sunrise-1500x1500-hero-eeae10efeb134a3e9d5a3852b1b6e7dc.jpg",
                            Instructions = "Pour tequila and orange juice into a glass with ice, then drizzle grenadine on top.",
                            Name = "Tequila Sunrise",
                            UserProfileId = 5
                        },
                        new
                        {
                            Id = 12,
                            Description = "A strong cocktail made with vodka, gin, rum, triple sec, lime juice, and soda water.",
                            GlassTypeId = 1,
                            Image = "https://robbreport.com/wp-content/uploads/2022/08/GettyImages_Long_Island_Iced_Tea.jpg?w=1000",
                            Instructions = "Shake all ingredients except soda water with ice, then strain into a glass and top up with soda water.",
                            Name = "Long Island Iced Tea",
                            UserProfileId = 6
                        },
                        new
                        {
                            Id = 13,
                            Description = "A savory cocktail made with vodka, tomato juice, and lemon juice.",
                            GlassTypeId = 1,
                            Image = "https://vinepair.com/wp-content/uploads/2021/04/extraspicybloodymary_card.jpg",
                            Instructions = "Combine ingredients in a glass with ice, then stir gently.",
                            Name = "Bloody Mary",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 14,
                            Description = "A bitter and balanced cocktail made with gin, blue curacao, and bitters.",
                            GlassTypeId = 2,
                            Image = "https://www.liquor.com/thmb/zafM9xOaJsoNMu0SMRcFw_Fxv3w=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/kingston-negroni-720x720-primary1-ef87562fea8240de92dd09c36457a8c2.jpg",
                            Instructions = "Stir ingredients with ice, then strain into a glass over ice.",
                            Name = "Negroni",
                            UserProfileId = 2
                        },
                        new
                        {
                            Id = 15,
                            Description = "A vibrant cocktail made with vodka, blue curacao, and orange juice.",
                            GlassTypeId = 2,
                            Image = "https://ik.imagekit.io/vjt1kualr/drinks/blue_lagoon/main-image.jpg",
                            Instructions = "Shake all ingredients with ice, then strain into a chilled glass.",
                            Name = "Blue Lagoon",
                            UserProfileId = 3
                        });
                });

            modelBuilder.Entity("BoozeClues.Models.GlassType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GlassTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Martini Glass"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Highball Glass"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Old Fashioned Glass"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Collins Glass"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Coupe Glass"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Wine Glass"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Champagne Flute"
                        });
                });

            modelBuilder.Entity("BoozeClues.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAlcoholic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAlcoholic = true,
                            Name = "Tequila"
                        },
                        new
                        {
                            Id = 2,
                            IsAlcoholic = false,
                            Name = "Lime Juice"
                        },
                        new
                        {
                            Id = 3,
                            IsAlcoholic = true,
                            Name = "Cointreau"
                        },
                        new
                        {
                            Id = 4,
                            IsAlcoholic = true,
                            Name = "Bourbon"
                        },
                        new
                        {
                            Id = 5,
                            IsAlcoholic = false,
                            Name = "Simple Syrup"
                        },
                        new
                        {
                            Id = 6,
                            IsAlcoholic = true,
                            Name = "Vodka"
                        },
                        new
                        {
                            Id = 7,
                            IsAlcoholic = true,
                            Name = "Gin"
                        },
                        new
                        {
                            Id = 8,
                            IsAlcoholic = true,
                            Name = "Rum"
                        },
                        new
                        {
                            Id = 9,
                            IsAlcoholic = true,
                            Name = "Triple Sec"
                        },
                        new
                        {
                            Id = 10,
                            IsAlcoholic = false,
                            Name = "Orange Juice"
                        },
                        new
                        {
                            Id = 11,
                            IsAlcoholic = false,
                            Name = "Cranberry Juice"
                        },
                        new
                        {
                            Id = 12,
                            IsAlcoholic = false,
                            Name = "Pineapple Juice"
                        },
                        new
                        {
                            Id = 13,
                            IsAlcoholic = false,
                            Name = "Ginger Beer"
                        },
                        new
                        {
                            Id = 14,
                            IsAlcoholic = false,
                            Name = "Mint Leaves"
                        },
                        new
                        {
                            Id = 15,
                            IsAlcoholic = true,
                            Name = "Bitters"
                        },
                        new
                        {
                            Id = 16,
                            IsAlcoholic = false,
                            Name = "Soda Water"
                        },
                        new
                        {
                            Id = 17,
                            IsAlcoholic = false,
                            Name = "Tonic Water"
                        },
                        new
                        {
                            Id = 18,
                            IsAlcoholic = false,
                            Name = "Lemon Juice"
                        },
                        new
                        {
                            Id = 19,
                            IsAlcoholic = true,
                            Name = "Maraschino Liqueur"
                        },
                        new
                        {
                            Id = 20,
                            IsAlcoholic = true,
                            Name = "Peach Schnapps"
                        },
                        new
                        {
                            Id = 21,
                            IsAlcoholic = false,
                            Name = "Grenadine"
                        },
                        new
                        {
                            Id = 22,
                            IsAlcoholic = true,
                            Name = "Blue Curacao"
                        },
                        new
                        {
                            Id = 23,
                            IsAlcoholic = true,
                            Name = "Amaretto"
                        },
                        new
                        {
                            Id = 24,
                            IsAlcoholic = true,
                            Name = "Kahlua"
                        },
                        new
                        {
                            Id = 25,
                            IsAlcoholic = false,
                            Name = "Coconut Cream"
                        });
                });

            modelBuilder.Entity("BoozeClues.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("CocktailRecipeId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.HasKey("CocktailRecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            CocktailRecipeId = 1,
                            IngredientId = 1
                        },
                        new
                        {
                            CocktailRecipeId = 1,
                            IngredientId = 2
                        },
                        new
                        {
                            CocktailRecipeId = 1,
                            IngredientId = 3
                        },
                        new
                        {
                            CocktailRecipeId = 2,
                            IngredientId = 4
                        },
                        new
                        {
                            CocktailRecipeId = 2,
                            IngredientId = 5
                        },
                        new
                        {
                            CocktailRecipeId = 2,
                            IngredientId = 15
                        },
                        new
                        {
                            CocktailRecipeId = 3,
                            IngredientId = 6
                        },
                        new
                        {
                            CocktailRecipeId = 3,
                            IngredientId = 9
                        },
                        new
                        {
                            CocktailRecipeId = 3,
                            IngredientId = 2
                        },
                        new
                        {
                            CocktailRecipeId = 3,
                            IngredientId = 11
                        },
                        new
                        {
                            CocktailRecipeId = 4,
                            IngredientId = 8
                        },
                        new
                        {
                            CocktailRecipeId = 4,
                            IngredientId = 5
                        },
                        new
                        {
                            CocktailRecipeId = 4,
                            IngredientId = 2
                        },
                        new
                        {
                            CocktailRecipeId = 4,
                            IngredientId = 14
                        },
                        new
                        {
                            CocktailRecipeId = 4,
                            IngredientId = 16
                        },
                        new
                        {
                            CocktailRecipeId = 5,
                            IngredientId = 8
                        },
                        new
                        {
                            CocktailRecipeId = 5,
                            IngredientId = 25
                        },
                        new
                        {
                            CocktailRecipeId = 5,
                            IngredientId = 12
                        },
                        new
                        {
                            CocktailRecipeId = 6,
                            IngredientId = 7
                        },
                        new
                        {
                            CocktailRecipeId = 6,
                            IngredientId = 22
                        },
                        new
                        {
                            CocktailRecipeId = 7,
                            IngredientId = 8
                        },
                        new
                        {
                            CocktailRecipeId = 7,
                            IngredientId = 19
                        },
                        new
                        {
                            CocktailRecipeId = 7,
                            IngredientId = 20
                        },
                        new
                        {
                            CocktailRecipeId = 7,
                            IngredientId = 18
                        },
                        new
                        {
                            CocktailRecipeId = 8,
                            IngredientId = 6
                        },
                        new
                        {
                            CocktailRecipeId = 8,
                            IngredientId = 2
                        },
                        new
                        {
                            CocktailRecipeId = 8,
                            IngredientId = 13
                        },
                        new
                        {
                            CocktailRecipeId = 9,
                            IngredientId = 4
                        },
                        new
                        {
                            CocktailRecipeId = 9,
                            IngredientId = 5
                        },
                        new
                        {
                            CocktailRecipeId = 9,
                            IngredientId = 18
                        },
                        new
                        {
                            CocktailRecipeId = 10,
                            IngredientId = 8
                        },
                        new
                        {
                            CocktailRecipeId = 10,
                            IngredientId = 5
                        },
                        new
                        {
                            CocktailRecipeId = 10,
                            IngredientId = 2
                        },
                        new
                        {
                            CocktailRecipeId = 11,
                            IngredientId = 1
                        },
                        new
                        {
                            CocktailRecipeId = 11,
                            IngredientId = 10
                        },
                        new
                        {
                            CocktailRecipeId = 11,
                            IngredientId = 21
                        },
                        new
                        {
                            CocktailRecipeId = 12,
                            IngredientId = 6
                        },
                        new
                        {
                            CocktailRecipeId = 12,
                            IngredientId = 7
                        },
                        new
                        {
                            CocktailRecipeId = 12,
                            IngredientId = 8
                        },
                        new
                        {
                            CocktailRecipeId = 12,
                            IngredientId = 9
                        },
                        new
                        {
                            CocktailRecipeId = 12,
                            IngredientId = 2
                        },
                        new
                        {
                            CocktailRecipeId = 12,
                            IngredientId = 16
                        },
                        new
                        {
                            CocktailRecipeId = 13,
                            IngredientId = 6
                        },
                        new
                        {
                            CocktailRecipeId = 13,
                            IngredientId = 10
                        },
                        new
                        {
                            CocktailRecipeId = 13,
                            IngredientId = 18
                        },
                        new
                        {
                            CocktailRecipeId = 14,
                            IngredientId = 7
                        },
                        new
                        {
                            CocktailRecipeId = 14,
                            IngredientId = 22
                        },
                        new
                        {
                            CocktailRecipeId = 14,
                            IngredientId = 15
                        },
                        new
                        {
                            CocktailRecipeId = 15,
                            IngredientId = 6
                        },
                        new
                        {
                            CocktailRecipeId = 15,
                            IngredientId = 22
                        },
                        new
                        {
                            CocktailRecipeId = 15,
                            IngredientId = 10
                        });
                });

            modelBuilder.Entity("BoozeClues.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Admina",
                            IdentityUserId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            LastName = "Strator"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "John",
                            IdentityUserId = "d8d76512-74f1-43bb-b1fd-87d3a8aa36df",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Jane",
                            IdentityUserId = "a7d21fac-3b21-454a-a747-075f072d0cf3",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Alice",
                            IdentityUserId = "c806cfae-bda9-47c5-8473-dd52fd056a9b",
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Bob",
                            IdentityUserId = "9ce89d88-75da-4a80-9b0d-3fe58582b8e2",
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Eve",
                            IdentityUserId = "d224a03d-bf0c-4a05-b728-e3521e45d74d",
                            LastName = "Davis"
                        });
                });

            modelBuilder.Entity("CocktailRecipeIngredient", b =>
                {
                    b.Property<int>("CocktailRecipesId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientsId")
                        .HasColumnType("integer");

                    b.HasKey("CocktailRecipesId", "IngredientsId");

                    b.HasIndex("IngredientsId");

                    b.ToTable("CocktailRecipeIngredient");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c3aaeb97-d2ba-4a53-a521-4eea61e59b35",
                            Name = "Admin",
                            NormalizedName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "605d20c7-d5b3-4c92-8598-0aca94f5005a",
                            Email = "admina@strator.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEJqHxJFYShUwETvxArbLhG2R9kkhvzHbuekfXB2O9iMCfgeHlH3Ynt/KvEvPuBzEfQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "83667d75-df59-48d7-9dd7-69078dd4d3ba",
                            TwoFactorEnabled = false,
                            UserName = "Administrator"
                        },
                        new
                        {
                            Id = "d8d76512-74f1-43bb-b1fd-87d3a8aa36df",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "78ed81d5-5c61-4e63-b6cd-37aa6d4519ea",
                            Email = "john@doe.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEAFS7N7yyNFCWLHGqA1nR/TrtSNAOV3KVWjKLkpcEs3Y1E3J7+oncTaLnbAJbYWfPQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6a2d15b8-2f62-492a-bbdb-880af8052e51",
                            TwoFactorEnabled = false,
                            UserName = "JohnDoe"
                        },
                        new
                        {
                            Id = "a7d21fac-3b21-454a-a747-075f072d0cf3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d1db2e58-2f10-4bb3-b326-b39bbe411bdd",
                            Email = "jane@smith.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEHsuejOJl3ZdY/UMQOQRIsc8QbGiGvcVrAZ7543eRcDUb/gLkEmiqPgrnMC3RSnT4A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ddbaa7cf-de52-4a44-8897-1d2acbc690a1",
                            TwoFactorEnabled = false,
                            UserName = "JaneSmith"
                        },
                        new
                        {
                            Id = "c806cfae-bda9-47c5-8473-dd52fd056a9b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4372cf40-8a56-491b-a7a5-3e4527e51670",
                            Email = "alice@johnson.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEGg/lpc+fk/ovVNdZhEaSjXce9oJkCcX5r3Raj3PRRqpvljunMEZT8PflTydjP0y6A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f5f42ade-6ef0-47d6-a070-aa495caf212a",
                            TwoFactorEnabled = false,
                            UserName = "AliceJohnson"
                        },
                        new
                        {
                            Id = "9ce89d88-75da-4a80-9b0d-3fe58582b8e2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7332c7be-7197-4f07-97f0-b3c2473b2b21",
                            Email = "bob@williams.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEMpozTLuFcaYAeiPzzhhCK3uVm/riSADxM0moMysuZY38Gshh2YJflN1cvAm2Vs66w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0129f906-d8f5-4729-b865-b2a7d8c19b4e",
                            TwoFactorEnabled = false,
                            UserName = "BobWilliams"
                        },
                        new
                        {
                            Id = "d224a03d-bf0c-4a05-b728-e3521e45d74d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "51738b56-dc8c-4399-923d-1ea54d9f598d",
                            Email = "eve@davis.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEBqt43ekniyh5h6ZeATfyu2oSz2AxHe9kbX9j/ZsuSH581GBHXfEKr5wZQomgK0n1A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "73ff80e4-9264-44fb-9d76-95cf27121ce4",
                            TwoFactorEnabled = false,
                            UserName = "EveDavis"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            RoleId = "c3aaeb97-d2ba-4a53-a521-4eea61e59b35"
                        },
                        new
                        {
                            UserId = "d8d76512-74f1-43bb-b1fd-87d3a8aa36df",
                            RoleId = "c3aaeb97-d2ba-4a53-a521-4eea61e59b35"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BoozeClues.Models.CocktailRecipe", b =>
                {
                    b.HasOne("BoozeClues.Models.GlassType", "GlassType")
                        .WithMany("CocktailRecipe")
                        .HasForeignKey("GlassTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoozeClues.Models.UserProfile", "UserProfile")
                        .WithMany("CocktailRecipes")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GlassType");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("BoozeClues.Models.RecipeIngredient", b =>
                {
                    b.HasOne("BoozeClues.Models.CocktailRecipe", "CocktailRecipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("CocktailRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoozeClues.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CocktailRecipe");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("BoozeClues.Models.UserProfile", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("CocktailRecipeIngredient", b =>
                {
                    b.HasOne("BoozeClues.Models.CocktailRecipe", null)
                        .WithMany()
                        .HasForeignKey("CocktailRecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoozeClues.Models.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BoozeClues.Models.CocktailRecipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("BoozeClues.Models.GlassType", b =>
                {
                    b.Navigation("CocktailRecipe");
                });

            modelBuilder.Entity("BoozeClues.Models.UserProfile", b =>
                {
                    b.Navigation("CocktailRecipes");
                });
#pragma warning restore 612, 618
        }
    }
}
